import { FileText } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { useLocation } from "react-router";
import { EmptyState } from "@/components/common/EmptyState";
import { ArticleContentCard } from "@/features/content-generation/components/ArticleContentCard";
import { ArticleEditChatCard } from "@/features/content-generation/components/ArticleEditChatCard";
import { DownloadDocumentButton } from "@/features/content-generation/components/DownloadDocumentButton";
import { FaqCard } from "@/features/content-generation/components/FaqCard";
import { GeneratingArticleLoader } from "@/features/content-generation/components/GeneratingArticleLoader";
import { ImagePromptCard } from "@/features/content-generation/components/ImagePromptCard";
import { PlagiarismCard } from "@/features/content-generation/components/PlagiarismCard";
import { RatingsCard } from "@/features/content-generation/components/RatingsCard";
import { SeoMetaCard } from "@/features/content-generation/components/SeoMetaCard";
import { UrlInputCard } from "@/features/content-generation/components/UrlInputCard";
import { useActiveProject } from "@/hooks/useActiveProject";
import { useGenerateContent, useGenerateContentFromTitle } from "@/hooks/queries/useContentGeneration";
import type { GeneratedContent } from "@/types/contentGeneration";

export function ContentGenerationPage() {
  const project = useActiveProject();
  const location = useLocation();
  const initialTitle = (location.state as { articleTitle?: string } | null)?.articleTitle;

  const urlMutation = useGenerateContent(project.id);
  const titleMutation = useGenerateContentFromTitle(project.id);
  const [content, setContent] = useState<GeneratedContent | null>(null);
  const [isEditOpen, setIsEditOpen] = useState(false);

  const isPending = urlMutation.isPending || titleMutation.isPending;
  const isError = urlMutation.isError || titleMutation.isError;
  const error = urlMutation.error ?? titleMutation.error;

  // Coming from the Article Title Generator tool: auto-generate the article
  // for the chosen title immediately, without requiring another click.
  const autoGeneratedFor = useRef<string | null>(null);
  useEffect(() => {
    if (!initialTitle || autoGeneratedFor.current === initialTitle) return;
    autoGeneratedFor.current = initialTitle;
    titleMutation.mutate(initialTitle, { onSuccess: setContent });
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [initialTitle]);

  return (
    <div className="flex flex-col gap-5">
      <UrlInputCard
        projectId={project.id}
        initialTitle={initialTitle}
        onGenerateFromUrl={(url) => urlMutation.mutate(url, { onSuccess: setContent })}
        onGenerateFromTitle={(title) => titleMutation.mutate(title, { onSuccess: setContent })}
        isGenerating={isPending}
      />

      {isError ? (
        <EmptyState
          icon={FileText}
          title="Couldn't generate the article"
          description={error instanceof Error ? error.message : "Please check the URL and try again."}
        />
      ) : null}

      {isPending ? <GeneratingArticleLoader /> : null}

      {!content && !isPending && !isError ? (
        <EmptyState
          icon={FileText}
          title="No article generated yet"
          description="Paste a product page URL, or enter a title/topic above, and click Generate to create a complete, SEO-optimized blog post ready to publish."
        />
      ) : null}

      {content ? (
        <>
          <div className="flex justify-end">
            <DownloadDocumentButton content={content} />
          </div>
          <SeoMetaCard content={content} />
          <RatingsCard seoRating={content.seoRating} aeoRating={content.aeoRating} geoRating={content.geoRating} />
          <ArticleContentCard content={content} onEditWithAi={() => setIsEditOpen(true)} />
          <ArticleEditChatCard
            projectId={project.id}
            content={content}
            onContentChange={setContent}
            open={isEditOpen}
            onOpenChange={setIsEditOpen}
          />
          <PlagiarismCard projectId={project.id} contentHtml={content.contentHtml} />
          <FaqCard faqs={content.faqs} faqJsonLd={content.faqJsonLd} />
          <ImagePromptCard imagePrompt={content.imagePrompt} />
        </>
      ) : null}
    </div>
  );
}
